services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: slim_app
    restart: always
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - "8001:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=postcodes
      - DB_USER=root
      - DB_PASS=root

  db:
    image: mysql:8.0
    container_name: slim_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: postcodes
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      retries: 5
      start_period: 10s

volumes:
  db_data:
